#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

# Install rclone for WebDAV support
apt-get install -y rclone

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin WebDAV "<span>&#128194;</span> WebDAV plugin has finished installing."

